const arr = [
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe One Bedroom Suite",
        RoomTypeCode: 4541,
        RoomTypeSupplierCode: "A1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21573",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP4",
        RatePlanId: 21573,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 4310.86,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20210601,
                    ToDate: 20240228,
                    PercentOrAmt: "P",
                    Value: "100.0",
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 4310.86,
        RateBeforeTax: 4310.86,
        TotalDiscount: 0,
        RecommendedRetailPrice: 5388.58,
        ContractLabel: "Room only Rate. Inclusive of basic WiFi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe One Bedroom Suite",
        RoomTypeCode: 4541,
        RoomTypeSupplierCode: "A1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 5209.92,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 5209.92,
        RateBeforeTax: 5209.92,
        TotalDiscount: 0,
        RecommendedRetailPrice: 6512.4,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe One Bedroom Suite",
        RoomTypeCode: 4541,
        RoomTypeSupplierCode: "A1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 5071.6,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 5071.6,
        RateBeforeTax: 5071.6,
        TotalDiscount: 0,
        RecommendedRetailPrice: 6339.5,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Presidential Three Bedroom Suite",
        RoomTypeCode: 4545,
        RoomTypeSupplierCode: "D3K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 17635.34,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 17635.34,
        RateBeforeTax: 17635.34,
        TotalDiscount: 0,
        RecommendedRetailPrice: 22044.17,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Presidential Three Bedroom Suite",
        RoomTypeCode: 4545,
        RoomTypeSupplierCode: "D3K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 17773.65,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 17773.65,
        RateBeforeTax: 17773.65,
        TotalDiscount: 0,
        RecommendedRetailPrice: 22217.07,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Presidential Three Bedroom Suite",
        RoomTypeCode: 4545,
        RoomTypeSupplierCode: "D3K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21573",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP4",
        RatePlanId: 21573,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 14990.04,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20210601,
                    ToDate: 20240228,
                    PercentOrAmt: "P",
                    Value: "100.0",
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 14990.04,
        RateBeforeTax: 14990.04,
        TotalDiscount: 0,
        RecommendedRetailPrice: 18737.54,
        ContractLabel: "Room only Rate. Inclusive of basic WiFi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Minsters Deluxe Two Bedroom Suite",
        RoomTypeCode: 4544,
        RoomTypeSupplierCode: "AS2",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21563",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP5",
        RatePlanId: 21563,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 7103.12,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 7103.12,
        RateBeforeTax: 7103.12,
        TotalDiscount: 0,
        RecommendedRetailPrice: 8878.9,
        ContractLabel: "Rate includes breakfast and basic Wi-Fi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Minsters Deluxe Two Bedroom Suite",
        RoomTypeCode: 4544,
        RoomTypeSupplierCode: "AS2",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 8494.93,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 8494.93,
        RateBeforeTax: 8494.93,
        TotalDiscount: 0,
        RecommendedRetailPrice: 10618.66,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Minsters Deluxe Two Bedroom Suite",
        RoomTypeCode: 4544,
        RoomTypeSupplierCode: "AS2",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 8356.61,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 8356.61,
        RateBeforeTax: 8356.61,
        TotalDiscount: 0,
        RecommendedRetailPrice: 10445.77,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Falconers Two Bedroom Suite",
        RoomTypeCode: 4543,
        RoomTypeSupplierCode: "BS2",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21563",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP5",
        RatePlanId: 21563,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 4898.7,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 4898.7,
        RateBeforeTax: 4898.7,
        TotalDiscount: 0,
        RecommendedRetailPrice: 6123.38,
        ContractLabel: "Rate includes breakfast and basic Wi-Fi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Falconers Two Bedroom Suite",
        RoomTypeCode: 4543,
        RoomTypeSupplierCode: "BS2",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 5901.5,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 5901.5,
        RateBeforeTax: 5901.5,
        TotalDiscount: 0,
        RecommendedRetailPrice: 7376.87,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Falconers Two Bedroom Suite",
        RoomTypeCode: 4543,
        RoomTypeSupplierCode: "BS2",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 5763.18,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 5763.18,
        RateBeforeTax: 5763.18,
        TotalDiscount: 0,
        RecommendedRetailPrice: 7203.98,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe Junior Suite",
        RoomTypeCode: 4537,
        RoomTypeSupplierCode: "B1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21563",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP5",
        RatePlanId: 21563,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 2326.9,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 2326.9,
        RateBeforeTax: 2326.9,
        TotalDiscount: 0,
        RecommendedRetailPrice: 2908.63,
        ContractLabel: "Rate includes breakfast and basic Wi-Fi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe Junior Suite",
        RoomTypeCode: 4537,
        RoomTypeSupplierCode: "B1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 2737.51,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 2737.51,
        RateBeforeTax: 2737.51,
        TotalDiscount: 0,
        RecommendedRetailPrice: 3421.89,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Junior Suite",
        RoomTypeCode: 4555,
        RoomTypeSupplierCode: "CS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21563",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP5",
        RatePlanId: 21563,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 1959.48,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 1959.48,
        RateBeforeTax: 1959.48,
        TotalDiscount: 0,
        RecommendedRetailPrice: 2449.35,
        ContractLabel: "Rate includes breakfast and basic Wi-Fi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Junior Suite",
        RoomTypeCode: 4555,
        RoomTypeSupplierCode: "CS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 2443.59,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 2443.59,
        RateBeforeTax: 2443.59,
        TotalDiscount: 0,
        RecommendedRetailPrice: 3054.49,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Junior Suite",
        RoomTypeCode: 4555,
        RoomTypeSupplierCode: "CS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 2305.27,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 2305.27,
        RateBeforeTax: 2305.27,
        TotalDiscount: 0,
        RecommendedRetailPrice: 2881.59,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe Junior Suite",
        RoomTypeCode: 4537,
        RoomTypeSupplierCode: "B1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 2875.83,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 2875.83,
        RateBeforeTax: 2875.83,
        TotalDiscount: 0,
        RecommendedRetailPrice: 3594.78,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Falconers One Bedroom Suite",
        RoomTypeCode: 4539,
        RoomTypeSupplierCode: "BS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21563",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP5",
        RatePlanId: 21563,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3208.67,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 3208.67,
        RateBeforeTax: 3208.67,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4010.84,
        ContractLabel: "Rate includes breakfast and basic Wi-Fi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Falconers One Bedroom Suite",
        RoomTypeCode: 4539,
        RoomTypeSupplierCode: "BS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3913.2,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 3913.2,
        RateBeforeTax: 3913.2,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4891.5,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Falconers One Bedroom Suite",
        RoomTypeCode: 4539,
        RoomTypeSupplierCode: "BS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3774.88,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 3774.88,
        RateBeforeTax: 3774.88,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4718.61,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Kings One Bedroom Suite",
        RoomTypeCode: 4538,
        RoomTypeSupplierCode: "AS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21563",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP5",
        RatePlanId: 21563,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3208.67,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 3208.67,
        RateBeforeTax: 3208.67,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4010.84,
        ContractLabel: "Rate includes breakfast and basic Wi-Fi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings One Bedroom Suite",
        RoomTypeCode: 4538,
        RoomTypeSupplierCode: "AS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3913.2,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 3913.2,
        RateBeforeTax: 3913.2,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4891.5,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings One Bedroom Suite",
        RoomTypeCode: 4538,
        RoomTypeSupplierCode: "AS1",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3774.88,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 3774.88,
        RateBeforeTax: 3774.88,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4718.61,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Minsters One Bedroom Suite",
        RoomTypeCode: 4540,
        RoomTypeSupplierCode: "C1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21563",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP5",
        RatePlanId: 21563,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3208.67,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 3208.67,
        RateBeforeTax: 3208.67,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4010.84,
        ContractLabel: "Rate includes breakfast and basic Wi-Fi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Minsters One Bedroom Suite",
        RoomTypeCode: 4540,
        RoomTypeSupplierCode: "C1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3913.2,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 3913.2,
        RateBeforeTax: 3913.2,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4891.5,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Minsters One Bedroom Suite",
        RoomTypeCode: 4540,
        RoomTypeSupplierCode: "C1K",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 3774.88,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 3774.88,
        RateBeforeTax: 3774.88,
        TotalDiscount: 0,
        RecommendedRetailPrice: 4718.61,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe Three Bedroom Suite",
        RoomTypeCode: 4554,
        RoomTypeSupplierCode: "AS3",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21563",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWSP5",
        RatePlanId: 21563,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 7837.93,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "Y",
        DynamicYN: "Y",
        TotalRate: 7837.93,
        RateBeforeTax: 7837.93,
        TotalDiscount: 0,
        RecommendedRetailPrice: 9797.41,
        ContractLabel: "Rate includes breakfast and basic Wi-Fi. Taxes extra.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe Three Bedroom Suite",
        RoomTypeCode: 4554,
        RoomTypeSupplierCode: "AS3",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21577",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWBB",
        RatePlanId: 21577,
        MealPlan: "Breakfast",
        MealPlanCode: "7",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 9359.41,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 9359.41,
        RateBeforeTax: 9359.41,
        TotalDiscount: 0,
        RecommendedRetailPrice: 11699.26,
        ContractLabel:
            "Rate inclusive of breakfast, Standard Internet and VAT. \r\nFlexible cancellation policy. \r\nNo minimum length of stay required.",
        MealPlanCodeLong: 7,
    },
    {
        RoomNo: 1,
        RoomType: "Kings Deluxe Three Bedroom Suite",
        RoomTypeCode: 4554,
        RoomTypeSupplierCode: "AS3",
        MealPlanSupplierCode: "RO",
        RoomStatus: "OK",
        BlackOut: {
            Status: "",
            Msg: "",
        },
        CurrCode: "USD",
        ContractTokenId: "21578",
        RoomConfigurationId: 1,
        RatePlanCode: "OIWFR",
        RatePlanId: 21578,
        MealPlan: "Room Only",
        MealPlanCode: "28",
        NumberOfMeals: 2,
        RoomNumber: 1,
        Rate: 9221.09,
        RoomStatusDetails: {
            Status: ["OK", "OK", "OK"],
        },
        DiscountDetails: {},
        CancellationPolicyDetails: {
            Cancellation: [
                {
                    FromDate: 20240223,
                    FromTime: "1400",
                    ToDate: 20240228,
                    NightToCharge: 1,
                },
            ],
        },
        PromotionalContract: "N",
        PackageYN: "N",
        NonRefundable: "N",
        DynamicYN: "Y",
        TotalRate: 9221.09,
        RateBeforeTax: 9221.09,
        TotalDiscount: 0,
        RecommendedRetailPrice: 11526.36,
        ContractLabel:
            "Best Available Rate, is the lowest available rate of the day with a flexible cancellation. \r\nRoom only rate. \r\nNo minimum length of stay required. \r\nInclusive of Internet and V.A.T.",
        MealPlanCodeLong: 28,
    },
];

let min = Infinity;

arr.forEach((el) => {
    if (el.RecommendedRetailPrice < min) {
        min = el.RecommendedRetailPrice;
    }
    console.log(el.RecommendedRetailPrice);
});

console.log("rrp :: ", min);
